import pandas as pd
# properties file
import props as props
# code from other files
import helper as hp

# create individual summary data
def indi_summary(df):
	# init empty result dataframe
	result = pd.DataFrame(columns = props.INDI_SUMMARY_HEADER)
	# unique individuals
	people = df['Owner'].unique().tolist()
	# unique product categories
	groups = df['Product Category'].unique().tolist()
	# iterate over the set of people
	for person in people:
		# check all groups for that person
		for cat in groups:
			data = df.loc[
			(
				(df['Owner'] == person) # if person is owner
				| (df['Shared to 1'] == person) # if person is part of shared 1
				| (df['Shared to 1'] == person) # if person is part of shared 2
			) # data for that person 
			& (df['Product Category'] == cat) # and that category
			& (df['Contract ID (Opportunity Id)'].notnull()) # non null contract number
			& (df['Contract ID (Opportunity Id)'] != '0') # some rows have contract id set to 0
			& (df['Actual Close Date - autogenerated (Opportunity Id)'] > props.CLOSE_DATE)
			, :]
			
			# calculate total revenue and total leads for one person + one product group
			revenue, leads = hp.revenue_lead_individual(data) # helper.py 
			# append row to result
			result = result.append({'person': person 
				, 'product-group': cat
				, 'number-of-orders': data.shape[0]
				, 'total-revenue': revenue
				, 'total-leads': leads
				}, ignore_index=True)

	return result